its-be/be/views.py
import json

from flask import Blueprint, abort, jsonify, redirect, render_template, request, url_for
from flask import Blueprint, abort, jsonify, render_template, request
from flask_login import login_required, current_user
from pony.flask import db_session
from pony.orm import select
from be.ml import generate_learning_material
from be.models.tutor import UserCourseSelection

from be.stats import get_topics_for_learning_material

from .models import Course, Test, Question, UserAnswer, Topic

views = Blueprint('views', __name__)
course = Blueprint('course', __name__)

@views.route('/', methods=['GET'])
def default():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    return render_template('auth/login.html')

@views.route('/its', methods=['GET'])
def its():
    return render_template("its.html")

@views.route('/courses', methods=['GET', 'POST'])
def courses():
    return render_template("courses.html")

@views.route('/user_home', methods=['GET', 'POST'])
@login_required
def home():
    enrolled_courses = current_user.enrolled_courses.course
    available_courses = Course.select(lambda c: c not in enrolled_courses)
    return render_template("user_home.html", enrolled_courses=enrolled_courses, available_courses=available_courses)

@course.route('/course/<int:course_id>', methods=['GET'])
@login_required
@db_session
def course_details(course_id):
    course = Course.get(id = course_id)
    user_is_enrolled = course in current_user.enrolled_courses.course
    if not course:
        abort(404)
    topics = []
    completed_tests = []
    incomplete_tests = []
    if user_is_enrolled:
        usc = UserCourseSelection[current_user, course]
        topics = usc.topics
        for test in usc.tests.filter(lambda t: t.completed):
            completed_tests.append(test)
        for test in usc.tests.filter(lambda t: not t.completed):
            incomplete_tests.append(test)
        print(completed_tests)
    available_topics = [topic for topic in course.topics if topic not in topics]
    return render_template("course_details.html", course = course.to_dict(), enrolled=user_is_enrolled, topics=topics, available_topics=available_topics, tests_comp=completed_tests, tests_incomp=incomplete_tests)

@views.route('/userTest', methods=['GET', 'POST'])
@login_required
def userTest():
    course_id=request.args.get('course_id')
    course = Course.get(id = course_id)
    test = Test.get(id=1)
    topics = [topic.topic for topic in course.topics]
    print(topics)
    return render_template("user_test.html", user=current_user, course_id=course_id, test=test, course=course, topics=topics)

@views.route('/userstats', methods=['GET', 'POST'])
@login_required
def userStats():
    return render_template("user_stats.html")

@views.route('/learning', methods=['GET'])
@login_required
def learning():
    course_id=request.args.get('course_id')
    course = Course.get(id = course_id)
    if not course:
        abort(404)
    if course not in current_user.enrolled_courses.course:
        abort(403)
    ucs = UserCourseSelection[current_user, course]
    print(ucs)
    learning_materials = generate_learning_material(course.name, ucs.topics)
    return render_template("learning.html", learning_materials=learning_materials, course=course)

@views.route('/submit_test', methods=['GET', 'POST'])
@login_required
def submit_test():
    test_id=request.args.get('test_id') 
    return render_template("submit_test.html", test_id=test_id)

    
@views.route('/aboutus', methods=['GET', 'POST'])
@login_required
def about_us():
    return render_template("about_us.html")

@views.route('/incompTest', methods=['GET', 'POST'])
@login_required
def IncompleteTest():
    test_id=request.args.get('test_id')
    return render_template("incomplete_test.html", test_id=test_id)

its-be/be/templates/about_us.html
{% extends 'base.html' %}

{% block title %} About Us {% endblock %}

{% block content %} 
<div class="container text-center my-5">
    <h1 class="mt-4">Welcome to Our Story</h1>
    <p class="lead">Discover the journey behind our Intelligent Tutoring System.</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h2 class="mb-3">Our Mission</h2>
            <p>We are committed to providing high-quality education and personalized learning experiences to empower individuals in their pursuit of knowledge.</p>
        </div>
        <div class="col-lg-6">
            <h2 class="mb-3">Our Vision</h2>
            <p>We envision a world where education is accessible to all, leveraging cutting-edge technology and innovative teaching methods.</p>
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2 class="text-center mb-4">Meet Our Team</h2>
            <div class="card-deck">
                <div class="card shadow">
                    <img src="{{ url_for('static', filename='team_member1.jpg') }}" alt="Team Member" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">RM</h5>
                        <p class="card-text">Creator & Developer</p>
                    </div>
                </div>
                <div class="card shadow">
                    <img src="{{ url_for('static', filename='team_member2.jpg') }}" alt="Team Member" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">JB</h5>
                        <p class="card-text">Creator & Developer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

its-be/be/templates/authBase.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
              <a class="nav-link" href="/auth/login">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/auth/register">Register</a>
            </li>
          </ul>
        </div>
        <div class="card-body">
          {% block authContent %}{% endblock %}
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap CSS and JavaScript -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

its-be/be/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}Test{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous" />
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  {% set login_page = 'auth.login' %}
  {% set register_page = 'auth.register' %}
  {% set current_page = request.endpoint %}
  {% set show_navbar = current_page not in [login_page, register_page] %}

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/its">ITS</a>
        <a class="navbar-brand" href="/user_home">Dashboard</a>
        <a class="navbar-brand" href="/courses">Courses</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/userstats"><i class="fa fa-user-circle"></i> User Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/auth/logout">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/auth/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/auth/register">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  {% for message in get_flashed_messages() %}
  <div class="flash">{{ message }}</div>
  {% endfor %}
  <div class="container">
    <main role="main" class="pb-3">

      {% block content %}{% endblock %}
      {% block testimonials %}{%endblock%}
      {% block benefits %}{%endblock%}
      {% block offers %}{%endblock%}
      {% block features %}{%endblock%}
      {% block coursecontent%}{%endblock%}

    </main>
  </div>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>

its-be/be/templates/course.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="style.css"> 
</head>
<body>
{% block title %}
  COURSES
 {% endblock %}
{% block coursecontent %}
<div class="heading"> 
    <h1> Courses </h1>
</div>
<br>
  <div class="course-details">
    <div class="course-maths">
        <div class="math-wrap">
            <img
              class="math-bg"
              src="static/math-course.avif"
              alt=""
            >
    <h2 class="text-center math-wrap">Mathematics Fundamentals</h2>
    <p class="course_description">This course is designed to strengthen students' foundational mathematical skills. Students will review and practice concepts in arithmetic, algebra, geometry, and basic statistics. The course aims to improve students' problem-solving abilities and mathematical reasoning.</p>
    <p class="course_description">Through interactive activities and real-world examples, students will gain a deeper understanding of mathematical principles and their practical applications. The course in future will also include opportunities for group discussions and collaborative problem-solving.</p>
    <p class="text-center"><b>Duration:</b> 10 weeks &emsp;&emsp;&emsp; <b>Pre-requisites:</b> Basic knowledge of arithmetic</p>
    </div>
  </div>
</div><br>
  <div class="course-details">
    <div class="course-earth-science">
        <div class="earth-wrap">
            <img
              class="earth-bg"
              src="static/earth-science-course.avif"
              alt=""
            >
    <h2 class="text-center earth-wrap">Introduction to Earth Sciences</h2>
    <p class="course_description">This course offers a comprehensive introduction to Earth sciences, covering topics such as geology, meteorology, and environmental science. Students will explore the Earth's structure, natural processes, weather patterns, and the impact of human activities on the environment.</p>
    <p class="course_description">The course includes engaging field trips, hands-on experiments, and interactive simulations to enhance students' understanding of Earth's dynamic systems. Students will also learn about sustainability and the importance of responsible environmental stewardship.</p>
    <p class="text-center"><b>Duration:</b> 12 weeks &emsp;&emsp;&emsp; <b>Pre-requisites:</b> None</p>
    </div>
  </div>
</div>
  <br>
  <div class="course-details">
    <div class="course-english">
        <div class="english-wrap">
            <img
              class="english-bg"
              src="static/english-course.avif"
              alt=""
            >
    <h2 class="text-center english-wrap">English Language Fundamentals</h2>
    <p class="course_description">This course is designed to help students improve their English language skills, focusing on reading, writing, speaking, and listening. The course covers essential grammar rules, vocabulary building, and effective communication strategies.</p>
    <p class="course_description">Students will engage in various activities, including discussions, debates, writing assignments, and reading comprehension exercises. They will also work on pronunciation and language fluency through interactive speaking exercises and language games.</p>
    <p class="course_description">Whether you're a beginner or looking to enhance your existing English skills, this course provides a supportive learning environment to help you become a more confident and proficient English speaker.</p>
    <p class="text-center"><b>Duration:</b> 8 weeks &emsp;&emsp;&emsp; <b>Pre-requisites:</b> Basic understanding of English</p>
    </div>   
   </div> 
</div>
{% endblock %}
</body>
</html>

its-be/be/templates/course_details.html
{% extends 'base.html' %}

{% block title %}Course Details{% endblock %}

{% block content %}

<div class="container mt-4">
  <h2>Course Details</h2>
  <ul>
    <li id="course_id" data-value="{{ course.id }}">Course ID: {{ course.id }}</li>
    <li>Course Name: {{ course.name }}</li>
  </ul>

  {% if enrolled %}
  <p>Enrollment Status: Enrolled</p>
  <p>Select Topics:</p>
  <form action="/api/topics" method="post">
    {% for topic in topics %}
    <div>
      <input type="checkbox" name="{{topic.topic}}" value="{{topic.topic}}" checked><label
      for="{{topic.topic}}">&emsp;{{topic.topic}}</label>
    </div>
    {% endfor %}
    {% for avt in available_topics %}
    <div>
      <input type="checkbox" name="{{avt.topic}}" value="{{avt.topic}}"><label for="{{avt.topic}}">&emsp;{{avt.topic}}</label>
    </div>
    {% endfor %}
  </ul>
    <input type="hidden" id="course" name="course" value="{{course.id}}" />
    <input type="submit" value="Update">
  </form>
  <button id="learn" class="btn btn-primary mt-3">Learn</button>
  <div id="loading-icon" class="d-none">
      <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  {% else %}
  <p>Enrollment Status: Not Enrolled</p>
  <button id="enroll-button" class="btn btn-primary mt-3">Enroll in Course</button>
  <p id="enrollment-status" class="mt-2"></p>
  <p href="#" id="refresh-link" class="btn btn-link mt-3"></p>
  {% endif %}

</div>
{% if enrolled %}
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <h2>Complete Tests</h2>
      <ul id="enrolled-courses" class="course-list">
        {% for test in tests_comp %}
        <li>
          <a href="/submit_test?test_id={{test.id}}" class="btn btn-link text-left">
            ID: {{ test.id }} 
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-md-6">
      <h2>Incomplete Tests</h2>
      <ul id="available-courses" class="course-list">
        {% for test in tests_incomp %}
        <li>
          <a href="/incompTest?test_id={{test.id}}" class="btn btn-link text-left">
            ID: {{ test.id }} 
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endif %}
<script>
const loadingIcon = document.getElementById('loading-icon');
document.addEventListener('DOMContentLoaded', function() {
const course_id = document.getElementById('course_id').getAttribute('data-value');
const refreshLink = document.getElementById('refresh-link');
  // Function to enroll the user in the course
  function enrollUserInCourse(course_id) {
    fetch('/api/course/enroll', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json' 
      },
      body: JSON.stringify({
        course_id: course_id
      })
    })
    .then(response => response.json())
    .then(data => {
      if (data.id.toString() === course_id) {
        document.getElementById('enrollment-status').textContent = 'Successfully Enrolled!';
        document.getElementById('enroll-button').disabled = true;
        window.location.reload(); 
      } else {
        document.getElementById('enrollment-status').textContent = 'Enrollment Failed. Please try again.';
      }
    })
    .catch(error => {
      console.error('Error enrolling in the course:', error);
      document.getElementById('enrollment-status').textContent = 'Enrollment Failed. Please try again.';
    });
  }
  const enrollButton = document.getElementById('enroll-button');
  if (enrollButton) {
    enrollButton.addEventListener('click', function() {
        console.log(course_id);
        enrollUserInCourse(course_id); // Pass the course ID to the enrollUserInCourse function
    });
  }
  // Add event listener for the Take Test button click
  const takeTestButton = document.getElementById('learn');
  if (takeTestButton) {
    takeTestButton.addEventListener('click', function() {
      loadingIcon.classList.remove('d-none');
        window.location.href = `/learning?course_id=${course_id}`; // Redirect to the "/userTest" page
    });
  }
});

</script>

<style>
  .content-wrapper {
      font-family: 'Roboto', sans-serif;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      border-radius: 10px;
      background-color: #ffffff;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
    }
  
    .content-wrapper h2 {
      text-align: center;
      margin-bottom: 20px;
    }
  
    .content-wrapper ul {
      list-style: none;
      padding: 0;
    }
  
    .content-wrapper li {
      margin-bottom: 10px;
    }
  
    .content-wrapper strong {
      font-weight: bold;
    }
  
  .spinner-border {
      width: 2rem;
      height: 2rem;
      border: 0.25em solid currentColor;
      border-right-color: transparent;
    }
  
  .spinner-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%; /* Make the container take up the full height */
  }
  /* Add more custom styles here as needed */
  /* Custom styling for the course lists */
  .course-list {
    list-style: none;
    padding: 0;
    margin: 0;
  }
  
  .course-list li {
    margin-bottom: 15px;
  }
  
  .course-list a {
    display: block;
    padding: 15px;
    border: 1px solid #ccc;
    background-color: #fff;
    color: #333;
    text-decoration: none;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    transition: background-color 0.3s ease, transform 0.3s ease;
  }
  
  .course-list a:hover {
    background-color: #f2f2f2;
    transform: translateY(-3px);
  }  
</style>
{% endblock %}

its-be/be/templates/courses.html
{% extends "base.html" %}
{% block title %}
  COURSES
{% endblock %}
{% block coursecontent %}
<div class="container my-5">
  <div class="row">
    <div class="col-lg-4">
        <center>
      <div class="course-details card shadow">
        <center>  <img src="{{ url_for('static', filename='math.png') }}" alt="Mathematics" class="card-img-top smaller-image">
        <div class="card-body">
          <h2 class="card-title">Mathematics</h2>
          <p class="card-text">Discover the beauty of mathematical concepts through lessons, quizzes and learning materials. Gain problem-solving skills. Strengthen your logical thinking and analytical skills as you dive into the world of mathematics.</p>
          <center><a href="{{ url_for('course.course_details', course_id=1) }}" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
        <center>
      <div class="course-details card shadow">
        <center>  <img src="{{ url_for('static', filename='science.png') }}" alt="Earth Sciences" class="card-img-top smaller-image">
        <div class="card-body">
          <h2 class="card-title">Science</h2>
          <p class="card-text"> Explore the mysteries of physics, chemistry, biology, and more. Engage in hands-on learning, discover the laws that govern our universe, and cultivate a curiosity-driven approach to understanding the world around us.</p>
          <center><a href="{{ url_for('course.course_details', course_id=2) }}" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <center>
    <div class="course-details card shadow">
      <center> <img src="{{ url_for('static', filename='history.png') }}" alt="English" class="card-img-top smaller-image">
      <div class="card-body">
        <h2 class="card-title">History</h2>
        <p class="card-text">Delve into the past to understand the great events, cultures, and individuals that have shaped our world. Explore fascinating narratives and perspectives that offer insights into our shared history.</p>
      <center><a href="{{ url_for('course.course_details', course_id=3) }}" class="btn btn-primary">Learn More</a>
      </div>
    </div>
  </div>
    <div class="col-lg-4">
        <center>
      <div class="course-details card shadow">
        <center> <img src="{{ url_for('static', filename='literature.png') }}" alt="English" class="card-img-top smaller-image">
        <div class="card-body">
          <h2 class="card-title">Literature</h2>
          <p class="card-text">Journey through literary masterpieces, explore diverse genres, and analyze the nuances of language and expression. Develop a deeper appreciation for the written word and the art of communication.</p>
        <center><a href="{{ url_for('course.course_details', course_id=4) }}" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
       
        <div class="col-lg-4">
            <center>
          <div class="course-details card shadow">
            <center> <img src="{{ url_for('static', filename='computer-science.png') }}" alt="English" class="card-img-top smaller-image">
            <div class="card-body">
              <h2 class="card-title">Computer Science</h2>
              <p class="card-text">Enter the realm of technology and explore the world of coding, development and algorithms. Create applications to solve real world problems with software.</p>
            <center><a href="{{ url_for('course.course_details', course_id=5) }}" class="btn btn-primary">Learn More</a>
            </div>
          </div>
        </div>
      <div class="col-lg-4">
        <center>
      <div class="course-details card shadow">
        <center>  <img src="{{ url_for('static', filename='languages.png') }}" alt="Earth Sciences" class="card-img-top smaller-image">
        <div class="card-body">
          <h2 class="card-title">Languages</h2>
          <p class="card-text"> Immerse yourself in the beauty of languages, develop your linguistic abilities, broaden your cultural horizons, and connect with   <br>  people  with diverse backgrounds  <br>  through the power of words.</p>
          <center><a href="{{ url_for('course.course_details', course_id=6) }}" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <center>
    <div class="course-details card shadow">
      <center>  <img src="{{ url_for('static', filename='social-studies.png') }}" alt="Mathematics" class="card-img-top smaller-image">
      <div class="card-body">
        <h2 class="card-title">Social Studies</h2>
        <p class="card-text">Explore the dynamics of societies, governments, and economies. Gain insights into the interconnectedness of global communities and the forces that shape our world.</p>
        <center><a href="{{ url_for('course.course_details', course_id=7) }}" class="btn btn-primary">Learn More</a>
      </div>
    </div>
  </div>
      <div class="col-lg-4">
        <center>
      <div class="course-details card shadow">
        <center> <img src="{{ url_for('static', filename='physical-edu.png') }}" alt="English" class="card-img-top smaller-image">
        <div class="card-body">
          <h2 class="card-title">Physical Education</h2>
          <p class="card-text">Enter the realm of tech and explore the world of coding and algorithms. Create apps to solve real world problems with software.</p>
        <center><a href="{{ url_for('course.course_details', course_id=8) }}" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
      </div>
    </div>

{% endblock %}

its-be/be/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="jumbotron text-center mt-5">
  <h1>Welcome to Your Intelligent Tutoring System</h1>
  <p class="lead">Discover, learn, and grow with us. Happy learning!</p>
  <a class="btn btn-primary" href="/aboutus" role="button">Learn More</a>
</div>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <h2>Enrolled Courses</h2>
      <ul id="enrolled-courses" class="course-list">
        {% for course in enrolled_courses %}
        <li>
          <a href="/course/{{ course.id }}" class="btn btn-link text-left">
            ID: {{ course.id }} - Name: {{ course.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
   <div class="col-md-6">
      <h2>Available Courses</h2>
      <ul id="available-courses" class="course-list">
        {% for course in available_courses %}
        <li>
          <a href="/course/{{ course.id }}" class="btn btn-link text-left">
            ID: {{ course.id }} - Name: {{ course.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
    </div> 
  </div>
</div>

<style>
  /* Custom styling for the course lists */
  .course-list {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .course-list li {
    margin-bottom: 10px;
  }

  .course-list a {
    display: block;
    padding: 10px;
    border: 1px solid #ddd;
    background-color: #f9f9f9;
    color: #333;
    text-decoration: none;
    transition: background-color 0.2s ease;
  }

  .course-list a:hover {
    background-color: #f2f2f2;
  }
</style>
{% endblock %}

its-be/be/templates/home_login.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="jumbotron text-center mt-5">
  <h1>Welcome to Your Intelligent Tutoring System</h1>
  <p class="lead">Discover, learn, and grow with us. Happy learning!</p>
  <a class="btn btn-primary" href="/course" role="button">Learn More</a>
</div>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <h2>Enrolled Courses</h2>
      <ul id="enrolled-courses" class="course-list">
        {% for course in enrolled_courses %}
        <li>
          <a href="/course/{{ course.id }}" class="btn btn-link text-left">
            ID: {{ course.id }} - Name: {{ course.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
   <div class="col-md-6">
      <h2>Available Courses</h2>
      <ul id="available-courses" class="course-list">
        {% for course in available_courses %}
        <li>
          <a href="/course/{{ course.id }}" class="btn btn-link text-left">
            ID: {{ course.id }} - Name: {{ course.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
    </div> 
  </div>
</div>

<style>
  /* Custom styling for the course lists */
  .course-list {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .course-list li {
    margin-bottom: 10px;
  }

  .course-list a {
    display: block;
    padding: 10px;
    border: 1px solid #ddd;
    background-color: #f9f9f9;
    color: #333;
    text-decoration: none;
    transition: background-color 0.2s ease;
  }

  .course-list a:hover {
    background-color: #f2f2f2;
  }
</style>
{% endblock %}

its-be/be/templates/submit_test.html
{% extends 'base.html' %}

{% block title %}Test Result{% endblock%}

{% block content %}
<div class="container mt-4">
  <h2>Test Result</h2>
  <ul class="list-group">
    <li id="test_id" data-value="{{ test_id }}" class="list-group-item">Test ID: {{ test_id }}</li>
  </ul>

  <div id="test-result-content" class="mt-4 d-none">
    <h3>Test Score: <span id="test-score"></span></h3>
    <ul id="test-result-list" class="list-group">
      <!-- Content will be populated dynamically here -->
    </ul>
  </div>
</div>

<script>
  const test_id = document.getElementById('test_id').getAttribute('data-value');

  function showTestResult(test_id) {
    fetch('/api/test/' + test_id)
      .then(response => response.json())
      .then(data => {
        console.log(data);

        // Populate the test result content
        const testResultContent = document.getElementById('test-result-content');
        const testScore = document.getElementById('test-score');
        testScore.textContent = data.score;

        const testList = document.getElementById('test-result-list');
        testList.innerHTML = ''; // Clear existing content

        data.questions.forEach(question => {
          const listItem = document.createElement('li');
          listItem.classList.add('list-group-item');

          // Check if the answer is correct or wrong and apply appropriate styling
          if (question.user_answer === question.answer) {
            listItem.classList.add('list-group-item-success'); // Green background for correct answer
          } else {
            listItem.classList.add('list-group-item-danger'); // Red background for wrong answer
          }

          listItem.innerHTML = `
            <strong>Question:</strong> ${question.question}<br>
            <strong>Your Answer:</strong> ${question.user_answer}<br>
            <strong>Correct Answer:</strong> ${question.answer}<br>
            <strong>Explanation:</strong> ${question.explanation}<br>
          `;
          testList.appendChild(listItem);
        });

        // Show the test result content
        testResultContent.classList.remove('d-none');
      })
      .catch(error => {
        console.error('Error getting the result:', error);
      });
  }

  document.addEventListener('DOMContentLoaded', () => {
    showTestResult(test_id);
  });
</script>
{% endblock %}